Adding setup.py (with install functionality) and test.py (to test imports, PyTorch, and TensorBoard)
PolicyEngine/reweight pull request #7
Opened 2024-06-14 17:40 UTC by pmberg

2024-06-15 02:34 UTC, MaxGhenis commented
Please make sure each PR closes at least one issue, and to use branches so you can work on multiple issues concurrently. I'd suggest the workflow of "start working on issue x" in VS Code's GitHub extension, as this assigns the issue to you, creates a new branch with the issue name, and links the PR to the issue.

2024-06-17 15:23 UTC, nikhilwoodruff requested changes
Thanks Peter!

Could you please:

* Add .egg-info to the .gitignore for this repo
* Also remove the tensorboard logs
* Add closed issues in this PR

2024-06-18 13:08 UTC, merged

2024-06-18 13:11 UTC, nikhilwoodruff commented on Makefile
> +	pip install -e .[dev]
test:
    pytest tests

2024-06-18 13:11 UTC, nikhilwoodruff commented on Makefile
> +	pip install -e .[dev]
Good point- actually reweight/tests